# Generated by Django 5.0.3 on 2024-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_image',
            field=models.CharField(default='', max_length=150),
        ),
    ]
