# Generated by Django 5.0.3 on 2024-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employee_emp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
