# Generated by Django 5.0.3 on 2024-04-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
