# Generated by Django 5.0.3 on 2024-04-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_employee_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_image',
        ),
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='static/assets/img'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
