# Generated by Django 5.0.3 on 2024-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_emp_designation_employee_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glr_image', models.ImageField(default='', upload_to='static/assets/img')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
