# Generated by Django 5.0.3 on 2024-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_gallery_alter_service_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='static/assets/img')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.TextField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=30)),
                ('stock', models.IntegerField()),
                ('is_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
