# Generated by Django 5.0.3 on 2024-04-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_appointment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='discounted_price',
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prodapp',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HR', 'HAIR'), ('SK', 'SKIN'), ('NL', 'NAIL'), ('BD', 'BODY')], default='', max_length=2),
        ),
    ]
