# Generated by Django 5.0.3 on 2024-04-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_details_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HR', 'hair'), ('SK', 'Skin'), ('NL', 'Nail'), ('BD', 'body')], default='', max_length=2),
        ),
    ]
