# Generated by Django 5.0.3 on 2024-04-29 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Vadodara', 'Vadodara'), ('Gandhinagar', 'Gandhinagar'), ('Bhavnagar', 'Bhavnagar'), ('Rajkot', 'Rajkot'), ('Bavla', 'Bavla'), ('Amreli', 'Amreli')], max_length=50)),
                ('state', models.CharField(default='GUJARAT', max_length=20)),
                ('pincode', models.IntegerField()),
                ('mobileno', models.BigIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
