# Generated by Django 5.0.3 on 2024-04-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment_method',
        ),
    ]
