# Generated by Django 5.0.3 on 2024-04-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_address_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Online', 'Online')], default='Online', max_length=50),
        ),
    ]
