# Generated by Django 5.0.3 on 2024-04-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_address_mobileno_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Total',
            new_name='total',
        ),
    ]
