# Generated by Django 5.0.3 on 2024-04-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_rename_total_orderplaced_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='addres',
            new_name='address',
        ),
    ]
